# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Assassin-Native' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'

  pod 'BaseLibrary', :path => '../BaseLibrary'

  target 'Assassin-NativeTests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 8.0.0'
    pod 'OHHTTPStubs/Swift'
  end
end
